[target.wasm32-unknown-emscripten]
linker = "./util/emcc"
rustflags = [
    "-C",
    "panic=abort",
    "-C",
    "link-args=-s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s FILESYSTEM=0 -s ENVIRONMENT=web,worker -s EXPORT_ES6=1 -s SINGLE_FILE=1 -s EXPORTED_RUNTIME_METHODS=HEAPU8",
]
