name: Checks

on:
  push:
    branches: ["main"]
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - uses: actions/checkout@v4
    - name: Setup pnpm
      run: |
        npm install -g pnpm@10.18.2
        pnpm setup
    - name: Lint
      run: |
        pnpm install
        pnpm run format-check
        pnpm run lint
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - uses: actions/checkout@v4
    - name: Setup pnpm
      run: |
        npm install -g pnpm@10.18.2
        pnpm setup
    - name: Test
      run: |
        pnpm install
        pnpm run test
